import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import i18n from "./index.i18n";
import { loadTranslations, useTranslations, I18nProps } from "@tsi18n/next";
import Link from "next/link";

export const getServerSideProps: GetServerSideProps<I18nProps> = async (cx) => {
  return {
    props: {
      tsi18n: loadTranslations(i18n, cx),
    },
  };
};

const Home: NextPage = () => {
  const t = useTranslations<typeof i18n, "home">("home");

  return (
    <div className={styles.container}>
      <Head>
        <title>TSI18n Example NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {t.hello} {t.world}
        </h1>
        <p>
          <Link href="/info">
            <a>Info</a>
          </Link>
        </p>
        <p>
          <Link locale="en" href="/">
            <a>en</a>
          </Link>
          <br />
          <Link locale="de" href="/">
            <a>de</a>
          </Link>
        </p>
      </main>
    </div>
  );
};

export default Home;
